# NOTE
# USED BY the package .launch files

#  The tf frame under which the images were published
camera_frame: arena_camera

#  The DeviceUserID of the camera. If empty, the first camera found in the
#  device list will be used
device_user_id: ""

#  The CameraInfo URL (Uniform Resource Locator) where the optional intrinsic
#  camera calibration parameters are stored. This URL string will be parsed
#  from the ROS-CameraInfoManager:
#  http://docs.ros.org/api/camera_info_manager/html/classcamera__info__manager_
#  1_1CameraInfoManager.html#details
camera_info_url: "camera_calibration.yaml"

#  The encoding of the pixels always rgb8

#  The desired publisher frame rate if listening to the topics.
#  This parameter can only be set once at startup
#  Calling the GrabImages-Action can result in a higher framerate
frame_rate: 30.0

#  Mode of camera's shutter. TDR054S only supports rolling shutter

##########################################################################
######################## Image Intensity Settings ########################
##########################################################################
# The following settings do *NOT* have to be set. Each camera has default
# values which provide an automatic image adjustment resulting in valid
# images
##########################################################################

#  The exposure time in microseconds to be set after opening the camera.
exposure_time: 10000.0

HDR_digital_clamping:  true
HDR_image_enhancement: true
HDR_saturation: 100
HDR_contrast: 50
HDR_brightness: 100
HDR_detail: 30
HDR_brightness_adjustement_frame_count: 1

device_stream_channel_packet_size: 9000
device_link_throughput_reserve: 30
stream_channel_packet_delay: 800
##########################################################################

#  The MTU size. Only used for GigE cameras.
#  To prevent lost frames configure the camera has to be configured
#  with the MTU size the network card supports. A value greater 3000
#  should be good (1500 for RaspberryPI)
# gige:
#  mtu_size: 9000
